/**
 * Discord webhook event type.
 * @see {@link https://docs.discord.com/developers/events/webhook-events#event-types}
 * @internal
 */
enum EventType {
	APPLICATION_AUTHORIZED = "APPLICATION_AUTHORIZED",
	APPLICATION_DEAUTHORIZED = "APPLICATION_DEAUTHORIZED",
	ENTITLEMENT_CREATE = "ENTITLEMENT_CREATE",
	ENTITLEMENT_DELETE = "ENTITLEMENT_DELETE",
	ENTITLEMENT_UPDATE = "ENTITLEMENT_UPDATE",
	GAME_DIRECT_MESSAGE_CREATE = "GAME_DIRECT_MESSAGE_CREATE",
	GAME_DIRECT_MESSAGE_DELETE = "GAME_DIRECT_MESSAGE_DELETE",
	GAME_DIRECT_MESSAGE_UPDATE = "GAME_DIRECT_MESSAGE_UPDATE",
	LOBBY_MESSAGE_CREATE = "LOBBY_MESSAGE_CREATE",
	LOBBY_MESSAGE_DELETE = "LOBBY_MESSAGE_DELETE",
	LOBBY_MESSAGE_UPDATE = "LOBBY_MESSAGE_UPDATE",
	QUEST_USER_ENROLLMENT = "QUEST_USER_ENROLLMENT"
}

export default EventType;
