/**
 * Discord guild feature.
 * @see {@link https://docs.discord.com/developers/resources/guild#guild-object-guild-features}
 * @internal
 */
enum GuildFeature {
	ANIMATED_BANNER = "ANIMATED_BANNER",
	ANIMATED_ICON = "ANIMATED_ICON",
	APPLICATION_COMMAND_PERMISSIONS_V2 = "APPLICATION_COMMAND_PERMISSIONS_V2",
	AUTO_MODERATION = "AUTO_MODERATION",
	BANNER = "BANNER",
	COMMUNITY = "COMMUNITY",
	CREATOR_MONETIZABLE_PROVISIONAL = "CREATOR_MONETIZABLE_PROVISIONAL",
	CREATOR_STORE_PAGE = "CREATOR_STORE_PAGE",
	DEVELOPER_SUPPORT_SERVER = "DEVELOPER_SUPPORT_SERVER",
	DISCOVERABLE = "DISCOVERABLE",
	ENHANCED_ROLE_COLORS = "ENHANCED_ROLE_COLORS",
	FEATURABLE = "FEATURABLE",
	GUESTS_ENABLED = "GUESTS_ENABLED",
	GUILD_TAGS = "GUILD_TAGS",
	INVITE_SPLASH = "INVITE_SPLASH",
	INVITES_DISABLED = "INVITES_DISABLED",
	MEMBER_VERIFICATION_GATE_ENABLED = "MEMBER_VERIFICATION_GATE_ENABLED",
	MORE_SOUNDBOARD = "MORE_SOUNDBOARD",
	MORE_STICKERS = "MORE_STICKERS",
	NEWS = "NEWS",
	PARTNERED = "PARTNERED",
	PREVIEW_ENABLED = "PREVIEW_ENABLED",
	RAID_ALERTS_DISABLED = "RAID_ALERTS_DISABLED",
	ROLE_ICONS = "ROLE_ICONS",
	ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE = "ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE",
	ROLE_SUBSCRIPTIONS_ENABLED = "ROLE_SUBSCRIPTIONS_ENABLED",
	SOUNDBOARD = "SOUNDBOARD",
	TICKETED_EVENTS_ENABLED = "TICKETED_EVENTS_ENABLED",
	VANITY_URL = "VANITY_URL",
	VERIFIED = "VERIFIED",
	VIP_REGIONS = "VIP_REGIONS",
	WELCOME_SCREEN_ENABLED = "WELCOME_SCREEN_ENABLED"
}

export default GuildFeature;
